export type Lang = "th" | "en";

export function getDict(lang: Lang): Dict {
  return dictionaries[lang] as Dict;
}

export const dictionaries = {
  th: {
    siteName: "98CarRent",
    siteSlogan: "รถเช่ามุกดาหาร · รถเช่าขับเอง · รถเช่าพร้อมคนขับ",
    nav: {
      home: "หน้าแรก",
      cars: "รถเช่า",
      gallery: "แกลเลอรี",
      booking: "จองรถ",
      tourism: "สถานที่ท่องเที่ยว",
      reviews: "รีวิว",
      contact: "ติดต่อเรา",
      call: "โทรหา",
      theme: "เปลี่ยนโทนสี",
      admin: "จัดการระบบ",
      login: "เข้าสู่ระบบ",
      logout: "ออกจากระบบ",
      language: "EN",
    },
    hero: {
      title: "เช่ารถขับเอง และพร้อมคนขับ",
      subtitle:
        "รถเช่ามุกดาหาร ครบวงจรทั้งรถเช่าขับเอง รถเช่าพร้อมคนขับ บริการมืออาชีพ ปลอดภัย สะดวก รวดเร็ว ทั้งจังหวัดมุกดาหารและนครพนม รวมถึงเที่ยวลาว",
      ctaBook: "จองรถเลย",
      ctaCars: "ดูรถของเรา",
    },
    home: {
      whyTitle: "ทำไมต้องเลือก 98CarRent",
      why1: "รถสภาพดี พร้อมใช้งาน",
      why1d: "รถทุกคันดูแลตรวจเช็คเป็นประจำ ปลอดภัยทุกเส้นทาง",
      why2: "ราคาตรงไปตรงมา",
      why2d: "ไม่มีค่าใช้จ่ายแอบแฝง คุ้มค่าทุกบาท",
      why3: "บริการรวดเร็ว 24 ชั่วโมง",
      why3d: "ตอบกลับเร็ว ทั้งโทรศัพท์และ Line",
      why4: "มีทั้งขับเองและพร้อมคนขับ",
      why4d: "เลือกตามความสะดวก เหมาะกับทุกทริป",
      featured: "รถแนะนำ",
      featuredSub: "รถยอดนิยมของเรา พร้อมให้คุณเช่า",
      viewAll: "ดูรถทั้งหมด",
      contactCta: "สอบถาม / จอง รถได้ทุกช่องทาง",
      contactCtaSub: "ทีมงานพร้อมให้บริการตลอด 24 ชั่วโมง",
      callNow: "โทรเลย",
      lineNow: "แอดไลน์",
      fbNow: "เยี่ยมชมเฟซบุ๊ก",
    },
    footer: {
      about: "บริการรถเช่ามุกดาหาร ครบวงจร ทั้งรถเช่าขับเองและรถเช่าพร้อมคนขับ บริการด้วยใจ ส่งถึงทุกจุดทั่วภาคอีสานและสะหวันนะเขต",
      quickLinks: "ลิงก์ด่วน",
      contact: "ช่องทางติดต่อ",
      rights: "สงวนลิขสิทธิ์",
    },
    car: {
      self: "ขับเอง",
      with_driver: "พร้อมคนขับ",
      available: "ว่าง",
      rented: "ถูกเช่า",
      maintenance: "ซ่อมบำรุง",
      pricePerDay: "บาท/วัน",
      priceDaily: "รายวัน",
      priceWeekly: "รายสัปดาห์",
      priceMonthly: "รายเดือน",
      priceNote:
        "ราคาพิเศษรายสัปดาห์และรายเดือน คุ้มกว่าชัดเจน — ติดต่อร้านเพื่อยืนยันวันว่างก่อนจอง",
      deposit: "มัดจำ",
      seats: "ที่นั่ง",
      transmission: "เกียร์",
      auto: "อัตโนมัติ",
      manual: "ธรรมดา",
      petrol: "เบนซิน",
      diesel: "ดีเซล",
      fuel: "เชื้อเพลิง",
      year: "ปี",
      plate: "ทะเบียน",
      book: "จองคันนี้",
      details: "ดูรายละเอียด",
      search: "ค้นหารถ...",
      allTypes: "ทุกแบบ",
      allStatuses: "ทุกสถานะ",
      noCars: "ไม่พบรถที่ค้นหา",
      description: "รายละเอียด",
      groupBy: "ประเภท",
      new: "เพิ่มรถใหม่",
      edit: "แก้ไข",
      delete: "ลบ",
      addPhoto: "เพิ่มรูป",
      photos: "รูปภาพ",
      emptyImage: "ยังไม่มีรูป",
    },
    booking: {
      title: "จองรถเช่า",
      subtitle:
        "กรอกข้อมูลเพื่อจองรถ ทีมงานจะติดต่อกลับเพื่อยืนยันภายใน 24 ชั่วโมง หรือโทรด่วน 061-5493256",
      step1: "เลือกวันที่และรถที่ต้องการ",
      step2: "ทีมงานติดต่อยืนยัน",
      step3: "รับรถและเที่ยวได้เลย",
      name: "ชื่อ-นามสกุล",
      phone: "เบอร์โทรศัพท์",
      line: "ไอดีไลน์ (ถ้ามี)",
      rentalType: "ประเภทการเช่า",
      car: "เลือกคันรถ",
      selectCar: "-- โปรดเลือกรถ --",
      startDate: "วันที่รับรถ",
      endDate: "วันที่คืนรถ",
      pickup: "จุดรับรถ",
      note: "หมายเหตุ (ถ้ามี)",
      submit: "ส่งคำขอจอง",
      success: "ส่งคำขอจองเรียบร้อย!",
      successDesc: "ทีมงานจะติดต่อกลับภายใน 24 ชั่วโมง เพื่อยืนยันการจอง",
      bookAgain: "จองคันอื่น",
      total: "ราคารวม",
      days: "วัน",
      pickSchool: "รับ-ส่งที่สนามบิน, โรงแรม หรือจุดที่กำหนด",
      requiredField: "กรุณากรอกข้อมูลให้ครบถ้วน",
      myBookingTitle: "ขั้นตอนการจอง",
      trackTitle: "เช็คสถานะการจอง",
      trackSubtitle: "กรอกรหัสอ้างอิงที่ได้รับหลังจอง เพื่อดูสถานะการยืนยัน",
      trackPlaceholder: "รหัสอ้างอิง เช่น 98-ABC234",
      trackButton: "ตรวจสอบ",
      refLabel: "รหัสอ้างอิง",
      trackNotFound: "ไม่พบการจองด้วยรหัสนี้ ลองตรวจสอบอีกครั้ง หรือติดต่อร้าน",
      trackStatus: "สถานะล่าสุด",
      dateBusy: "ช่วงวันที่เลือกชนกับวันว่างของรถคันนี้ กรุณาเลือกวันใหม่ หรือติดต่อร้าน",
      busyDates: "วันไม่ว่าง",
      months: ["ม.ค.", "ก.พ.", "มี.ค.", "เม.ย.", "พ.ค.", "มิ.ย.", "ก.ค.", "ส.ค.", "ก.ย.", "ต.ค.", "พ.ย.", "ธ.ค."],
      weekdays: ["อา", "จ", "อ", "พ", "พฤ", "ศ", "ส"],
      calHint: "วันที่จองแล้วจะเป็นสีเทา เลือกไม่ได้ — แตะวันที่เพื่อเลือก",
      statusPending: "รอการยืนยัน",
      statusConfirmed: "ยืนยันแล้ว",
      statusCanceled: "ยกเลิก",
      statusCompleted: "เสร็จสิ้น",
      withDriverNote: "รถพร้อมคนขับ รวมค่าบริการคนขับแล้ว (ไม่รวมน้ำมัน)",
    },
    tourism: {
      title: "สถานที่ท่องเที่ยว",
      subtitle:
        "แนะนำเส้นทางท่องเที่ยว มุกดาหาร และ นครพนม สำหรับทริปขับรถของคุณ",
      khor: "MUKDAHAN · NAKHON PHANOM",
      mukdahan: "มุกดาหาร",
      nakhonphanom: "นครพนม",
      explore: "เส้นทางแนะนำ",
      routeMk: "มุกดาหาร → หอแก้ว → ตลาดอินโดจีน → ภูผาเทิบ → เกาะก้านเหลือง",
      routeNp: "นครพนม → ถนนเฉลิมพฤกษ์ → พระธาตุพนม → ภูลังกา",
      tip: "ทิปส์",
      tipText:
        "ต้องมีใบขับขี่และบัตรประชาชนสำหรับเช่ารถขับเอง หากต้องการรถพร้อมคนขับ ทีมงานพร้อมบริการทุกจังหวัด",
      viaCar: "เช่ารถไปเที่ยวกับเรา",
    },
    review: {
      title: "รีวิวจากลูกค้า",
      subtitle: "ความประทับใจของลูกค้าที่ใช้บริการ 98CarRent",
      write: "เขียนรีวิว",
      name: "ชื่อของคุณ",
      rating: "คะแนน",
      comment: "ความคิดเห็น",
      imageLabel: "รูปภาพ (ถ้ามี)",
      submit: "ส่งรีวิว",
      success: "ขอบคุณสำหรับรีวิว!",
      ratePlaceholder: "แสดงความคิดเห็นเกี่ยวกับบริการ...",
      delete: "ลบรีวิว",
      noReview: "ยังไม่มีรีวิว เป็นคนแรกที่เขียนรีวิวเลย!",
    },
    gallery: {
      title: "แกลเลอรี",
      subtitle: "ภาพรถและบรรยากาศการบริการของเรา",
      add: "เพิ่มรูป",
      delete: "ลบรูป",
      caption: "คำอธิบาย",
      empty: "ยังไม่มีรูปในแกลเลอรี กรุณาเพิ่มจากหน้าแอดมิน",
      folders: "โฟลเดอร์",
      createFolder: "สร้างโฟลเดอร์",
      folderName: "ชื่อโฟลเดอร์",
      selectFolder: "เลือกโฟลเดอร์ (ไม่บังคับ)",
      multiplePhotos: "เพิ่มได้หลายรูปพร้อมกัน (เลือกหลายไฟล์)",
      noFolders: "ยังไม่มีโฟลเดอร์",
      uncategorized: "รูปทั่วไป",
    },
    contact: {
      title: "ติดต่อเรา",
      phoneTitle: "โทรศัพท์",
      lineTitle: "ไลน์",
      facebookTitle: "เฟซบุ๊ก",
      phone1: "061-5493256",
      phone2: "061-5474953",
      line1: "98CarRent",
      line2: "aoftaaof",
      address: "มุกดาหาร, ประเทศไทย",
      hours: "ให้บริการทุกวัน 08.00 - 22.00 น.",
    },
    dashboard: {
      title: "แดชบอร์ด",
      welcome: "ยินดีต้อนรับ",
      totalCars: "รถทั้งหมด",
      availableCars: "รถว่าง",
      totalBookings: "คำขอจองทั้งหมด",
      revenue: "รายได้ (เสร็จสิ้น)",
      pendingBookings: "รอการยืนยัน",
      monthlyBookings: "จำนวนจองรายเดือน",
      bookingStatus: "สัดส่วนสถานะการจอง",
      latestBookings: "คำขอจองล่าสุด",
      viewAll: "ดูทั้งหมด",
      turnover: "รายได้รวม (บาท)",
    },
    admin: {
      dashboard: "แดชบอร์ด",
      cars: "จัดการรถ",
      bookings: "จัดการการจอง",
      gallery: "แกลเลอรีรถ",
      reviews: "จัดการรีวิว",
      logout: "ออกจากระบบ",
      addCar: "เพิ่มรถ",
      editCar: "แก้ไขรถ",
      backToList: "กลับหน้ารายการ",
      actions: "จัดการ",
      status: "สถานะ",
      customer: "ลูกค้า",
      phone: "โทรศัพท์",
      dateRange: "ช่วงเช่า",
      carName: "รถ",
      createdAt: "วันที่จอง",
      noData: "ไม่พบข้อมูล",
      deleteCarConfirm: "ยืนยันการลบรถคันนี้?",
      deleteBookingConfirm: "ยืนยันการลบการจองนี้?",
      carSaved: "บันทึกรถเรียบร้อย",
      carDeleted: "ลบรถเรียบร้อย",
      bookingUpdated: "อัปเดตการจองเรียบร้อย",
      bookingDeleted: "ลบการจองเรียบร้อย",
      reviewDeleted: "ลบรีวิวเรียบร้อย",
      gallerySaved: "บันทึกรูปเรียบร้อย",
      galleryDeleted: "ลบรูปเรียบร้อย",
      save: "บันทึก",
      cancel: "ยกเลิก",
      bookingDetail: "รายละเอียดการจอง",
      markConfirmed: "ยืนยัน",
      markCompleted: "เสร็จสิ้น",
      markCanceled: "ยกเลิกจอง",
      markConfirmedConfirm: "ยืนยันการจองนี้? ลูกค้าจะเห็นสถานะเปลี่ยนเป็น 'ยืนยันแล้ว'",
      markCompletedConfirm: "ยืนยันว่าการเช่านี้เสร็จสิ้นแล้ว? สถานะจะเปลี่ยนเป็น 'เสร็จสิ้น'",
      markCanceledConfirm: "ยกเลิกการจองนี้? วันที่ในแผนจองจะเปิดให้จองใหม่ได้",
      carType: "ประเภทรถ",
      carDetails: "รายละเอียดรถ",
      loginRedirect: "เข้าสู่ระบบ",
    },
    login: {
      title: "เข้าสู่ระบบผู้ดูแล",
      subtitle: "สำหรับเจ้าของระบบเท่านั้น",
      username: "ชื่อผู้ใช้",
      password: "รหัสผ่าน",
      submit: "เข้าสู่ระบบ",
      error: "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
      backHome: "กลับหน้าแรก",
    },
    status: {
      all: "ทั้งหมด",
      pending: "รอการยืนยัน",
      confirmed: "ยืนยันแล้ว",
      canceled: "ยกเลิก",
      completed: "เสร็จสิ้น",
    },
    common: {
      loading: "กำลังโหลด...",
      submit: "ส่ง",
      back: "ย้อนกลับ",
      delete: "ลบ",
      edit: "แก้ไข",
      th: "ไทย",
      en: "English",
      baht: "บาท",
    },
  },
  en: {
    siteName: "98CarRent",
    siteSlogan: "Mukdahan Car Rental · Self-Drive · With Driver",
    nav: {
      home: "Home",
      cars: "Cars",
      gallery: "Gallery",
      booking: "Booking",
      tourism: "Tourism",
      reviews: "Reviews",
      contact: "Contact",
      call: "Call",
      theme: "Theme",
      admin: "Dashboard",
      login: "Login",
      logout: "Logout",
      language: "ไทย",
    },
    hero: {
      title: "Self-Drive & Chauffeur Car Rental",
      subtitle:
        "98CarRent in Mukdahan offers full-service car rental — self-drive and with driver. Professional, safe and fast, covering Mukdahan, Nakhon Phanom and beyond, including Laos trips.",
      ctaBook: "Book Now",
      ctaCars: "View Our Cars",
    },
    home: {
      whyTitle: "Why choose 98CarRent",
      why1: "Well-maintained fleet",
      why1d: "Every car is regularly serviced and safe on every road.",
      why2: "Transparent pricing",
      why2d: "No hidden fees — every baht well spent.",
      why3: "Fast 24h service",
      why3d: "Quick replies via phone and Line.",
      why4: "Self-drive or with driver",
      why4d: "Choose what suits your trip best.",
      featured: "Featured Cars",
      featuredSub: "Our most popular cars, ready for you",
      viewAll: "View All Cars",
      contactCta: "Ask or book through any channel",
      contactCtaSub: "Our team is here for you 24 hours a day.",
      callNow: "Call Now",
      lineNow: "Add us on Line",
      fbNow: "Visit our Facebook",
    },
    footer: {
      about:
        "Full-service car rental in Mukdahan — self-drive and with driver. Serving all of Isan and Savannakhet with heart.",
      quickLinks: "Quick Links",
      contact: "Contact",
      rights: "All rights reserved.",
    },
    car: {
      self: "Self-drive",
      with_driver: "With driver",
      available: "Available",
      rented: "Rented",
      maintenance: "Maintenance",
      pricePerDay: "THB/day",
      priceDaily: "Daily",
      priceWeekly: "Weekly",
      priceMonthly: "Monthly",
      priceNote:
        "Special weekly and monthly rates — contact the shop to confirm availability before booking",
      deposit: "Deposit",
      seats: "Seats",
      transmission: "Gear",
      auto: "Automatic",
      manual: "Manual",
      petrol: "Petrol",
      diesel: "Diesel",
      fuel: "Fuel",
      year: "Year",
      plate: "Plate",
      book: "Book This Car",
      details: "Details",
      search: "Search cars...",
      allTypes: "All types",
      allStatuses: "All statuses",
      noCars: "No cars found",
      description: "Description",
      groupBy: "Type",
      new: "Add New Car",
      edit: "Edit",
      delete: "Delete",
      addPhoto: "Add Photo",
      photos: "Photos",
      emptyImage: "No photo yet",
    },
    booking: {
      title: "Book a Car",
      subtitle:
        "Fill in the form to book. Our team will confirm within 24 hours, or call 061-5493256.",
      step1: "Choose your dates and car",
      step2: "Our team confirms your booking",
      step3: "Pick up the car and enjoy your trip",
      name: "Full name",
      phone: "Phone number",
      line: "Line ID (optional)",
      rentalType: "Rental type",
      car: "Choose car",
      selectCar: "-- Select a car --",
      startDate: "Pick-up date",
      endDate: "Return date",
      pickup: "Pick-up location",
      note: "Note (optional)",
      submit: "Send booking request",
      success: "Booking request sent!",
      successDesc: "We will contact you within 24 hours to confirm the booking.",
      bookAgain: "Book another car",
      total: "Total",
      days: "days",
      pickSchool: "Pick-up at airport, hotel or agreed point",
      requiredField: "Please fill in all required fields",
      myBookingTitle: "How to book",
      trackTitle: "Check booking status",
      trackSubtitle: "Enter the reference code you received after booking to see confirmation status",
      trackPlaceholder: "Reference code e.g. 98-ABC234",
      trackButton: "Check",
      refLabel: "Reference",
      trackNotFound: "No booking found with this code. Double-check or contact the shop",
      trackStatus: "Current status",
      dateBusy: "Selected dates overlap an existing booking for this car. Pick different dates or contact the shop",
      busyDates: "Unavailable dates",
      months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
      weekdays: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
      calHint: "Grey dates are already booked and cannot be selected — tap a date to choose",
      statusPending: "Pending",
      statusConfirmed: "Confirmed",
      statusCanceled: "Canceled",
      statusCompleted: "Completed",
      withDriverNote: "With-driver rates include the driver fee (fuel not included).",
    },
    tourism: {
      title: "Tourist Attractions",
      subtitle:
        "Recommended routes in Mukdahan and Nakhon Phanom for your road trip.",
      khor: "MUKDAHAN · NAKHON PHANOM",
      mukdahan: "Mukdahan",
      nakhonphanom: "Nakhon Phanom",
      explore: "Suggested routes",
      routeMk: "Mukdahan → Tower → Indo-China Market → Phu Pha Thoep → Ko Kan Lueang",
      routeNp: "Nakhon Phanom → Chaloem Phrakiat Rd → Phra That Phanom → Phu Langka",
      tip: "Tips",
      tipText:
        "A driving licence and ID card are required for self-drive rentals. Chauffeur service is available for every province.",
      viaCar: "Rent a car with us",
    },
    review: {
      title: "Customer Reviews",
      subtitle: "What our customers say about 98CarRent",
      write: "Write a review",
      name: "Your name",
      rating: "Rating",
      comment: "Comment",
      imageLabel: "Photo (optional)",
      submit: "Submit review",
      success: "Thank you for your review!",
      ratePlaceholder: "Share your experience...",
      delete: "Delete review",
      noReview: "No reviews yet — be the first!",
    },
    gallery: {
      title: "Gallery",
      subtitle: "Photos of our cars and services",
      add: "Add photo",
      delete: "Delete photo",
      caption: "Caption",
      empty: "No photos yet. Add some from the admin page.",
      folders: "Folders",
      createFolder: "Create folder",
      folderName: "Folder name",
      selectFolder: "Select folder (optional)",
      multiplePhotos: "Upload multiple photos at once (select many files)",
      noFolders: "No folders yet",
      uncategorized: "General",
    },
    contact: {
      title: "Contact Us",
      phoneTitle: "Phone",
      lineTitle: "Line",
      facebookTitle: "Facebook",
      phone1: "061-5493256",
      phone2: "061-5474953",
      line1: "98CarRent",
      line2: "aoftaaof",
      address: "Mukdahan, Thailand",
      hours: "Open daily 08.00 - 22.00",
    },
    dashboard: {
      title: "Dashboard",
      welcome: "Welcome",
      totalCars: "Total Cars",
      availableCars: "Available",
      totalBookings: "Total Bookings",
      revenue: "Revenue (Completed)",
      pendingBookings: "Pending",
      monthlyBookings: "Bookings per month",
      bookingStatus: "Booking status breakdown",
      latestBookings: "Latest bookings",
      viewAll: "View all",
      turnover: "Total revenue (THB)",
    },
    admin: {
      dashboard: "Dashboard",
      cars: "Manage Cars",
      bookings: "Manage Bookings",
      gallery: "Car Gallery",
      reviews: "Manage Reviews",
      logout: "Logout",
      addCar: "Add Car",
      editCar: "Edit Car",
      backToList: "Back to list",
      actions: "Actions",
      status: "Status",
      customer: "Customer",
      phone: "Phone",
      dateRange: "Rental period",
      carName: "Car",
      createdAt: "Booked on",
      noData: "No data",
      deleteCarConfirm: "Delete this car?",
      deleteBookingConfirm: "Delete this booking?",
      carSaved: "Car saved successfully",
      carDeleted: "Car deleted",
      bookingUpdated: "Booking updated",
      bookingDeleted: "Booking deleted",
      reviewDeleted: "Review deleted",
      gallerySaved: "Photo saved",
      galleryDeleted: "Photo deleted",
      save: "Save",
      cancel: "Cancel",
      bookingDetail: "Booking details",
      markConfirmed: "Confirm",
      markCompleted: "Complete",
      markCanceled: "Cancel booking",
      markConfirmedConfirm: "Confirm this booking? The customer will see the status change to 'Confirmed'",
      markCompletedConfirm: "Confirm this rental is complete? Status will change to 'Completed'",
      markCanceledConfirm: "Cancel this booking? The dates will become available for new bookings",
      carType: "Car type",
      carDetails: "Car details",
      loginRedirect: "Login",
    },
    login: {
      title: "Admin Login",
      subtitle: "For the owner only",
      username: "Username",
      password: "Password",
      submit: "Login",
      error: "Invalid username or password",
      backHome: "Back to home",
    },
    status: {
      all: "All",
      pending: "Pending",
      confirmed: "Confirmed",
      canceled: "Canceled",
      completed: "Completed",
    },
    common: {
      loading: "Loading...",
      submit: "Submit",
      back: "Back",
      delete: "Delete",
      edit: "Edit",
      th: "ไทย",
      en: "English",
      baht: "THB",
    },
  },
} as const;

export type Dict = (typeof dictionaries)["th"];